on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 19.x
      uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: npm install
      run: npm install
      
    - name: npm install jest
      run: npm install -g jest

    - name: test
      run: jest
    
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
